application: combine-it-the-game
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /third_party
  static_dir: third_party/dist

- url: /.*
  script: handler.py


skip_files:
 - README
 - LICENSE
 - third_party/(?:(?!dist).)*$
 - \.git
 - (.*/)?\..*
 - .*\.pyc
 - .*\.svg
